# Generated by Django 4.0.4 on 2022-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='proposal'),
        ),
    ]
